files:
  # UI переклад
  - source: /lang/en.json
    translation: /lang/%two_letters_code%.json

  # Контент для компендіумів (name + description у спрощених JSON)
  - source: /src-packs/en/**/*.json
    translation: /src-packs/%two_letters_code%/**/%original_file_name%
